// src/data/azkarData.js

const azkarData = [
  {
    id: 'azkar-sabah-masaa',
    category: 'أذكار الصباح والمساء',
    sections: [
      {
        id: 'sayyid-al-istighfar',
        text: 'اللهم أنت ربي لا إله إلا أنت، خلقتني وأنا عبدك، وأنا على عهدك ووعدك ما استطعت، أعوذ بك من شر ما صنعت، أبوء لك بنعمتك علي وأبوء بذنبي، فاغفر لي؛ فإنه لا يغفر الذنوب إلا أنت.',
        source: 'صحيح البخاري',
        repetition: 1,
        audio: '/audio/sayyid_al_istighfar.mp3',
      },
      {
        id: 'allahumma-bika-asbahna',
        text: 'اللهم بك أصبحنا وبك أمسينا، وبك نحيا وبك نموت وإليك النشور. (وفي المساء: اللهم بك أمسينا وبك أصبحنا، وبك نحيا وبك نموت وإليك المصير).',
        source: 'صحيح الترمذي',
        repetition: 1,
        audio: '/audio/allahumma_bika_asbahna.mp3',
      },
      {
        id: 'allahumma-inni-asbahtu-ushhiduka',
        text: 'اللهم إني أصبحت أشهدك وأشهد حملة عرشك وملائكتك وجميع خلقك، أنك أنت الله لا إله إلا أنت وحدك لا شريك لك، وأن محمداً عبدك ورسولك. (أربع مرات).',
        source: 'سنن أبي داود',
        repetition: 4,
        audio: '/audio/allahumma_inni_asbahtu_ushhiduka.mp3',
      },
      {
        id: 'allahumma-afini-fi-badani',
        text: 'اللهم عافني في بدني، اللهم عافني في سمعي، اللهم عافني في بصري، لا إله إلا أنت. (ثلاث مرات).',
        source: 'سنن أبي داود',
        repetition: 3,
        audio: '/audio/allahumma_afini_fi_badani.mp3',
      },
      {
        id: 'hasbiyallahu-la-ilaha-illa-hu',
        text: 'حسبي الله لا إله إلا هو عليه توكلت وهو رب العرش العظيم. (سبع مرات).',
        source: 'سنن أبي داود',
        repetition: 7,
        audio: '/audio/hasbiyallahu_la_ilaha_illa_hu.mp3',
      },
      {
        id: 'allahumma-inni-as-alukal-afwa',
        text: 'اللهم إني أسألك العفو والعافية في الدنيا والآخرة، اللهم إني أسألك العفو والعافية في ديني ودنياي وأهلي ومالي، اللهم استر عوراتي وآمن روعاتي، اللهم احفظني من بين يدي ومن خلفي وعن يميني وعن شمالي ومن فوقي وأعوذ بعظمتك أن أغتال من تحتي.',
        source: 'سنن أبي داود وابن ماجه',
        repetition: 1,
        audio: '/audio/allahumma_inni_as_alukal_afwa.mp3',
      },
      {
        id: 'allahumma-alimul-ghaybi',
        text: 'اللهم عالم الغيب والشهادة فاطر السماوات والأرض رب كل شيء ومليكه، أشهد أن لا إله إلا أنت، أعوذ بك من شر نفسي ومن شر الشيطان وشركه، وأن أقترف على نفسي سوءاً أو أجره إلى مسلم.',
        source: 'صحيح الترمذي وأبي داود',
        repetition: 1,
        audio: '/audio/allahumma_alimul_ghaybi.mp3',
      },
      {
        id: 'bismillahi-alladhi-la-yaduru',
        text: 'بسم الله الذي لا يضر مع اسمه شيء في الأرض ولا في السماء وهو السميع العليم. (ثلاث مرات).',
        source: 'صحيح الترمذي وأبي داود',
        repetition: 3,
        audio: '/audio/bismillahi_alladhi_la_yaduru.mp3',
      },
      {
        id: 'raditu-billahi-rabban',
        text: 'رضيت بالله رباً، وبالإسلام ديناً، وبمحمد صلى الله عليه وسلم نبياً ورسولاً. (ثلاث مرات).',
        source: 'صحيح أبي داود',
        repetition: 3,
        audio: '/audio/raditu_billahi_rabban.mp3',
      },
      {
        id: 'ya-hayyu-ya-qayyum',
        text: 'يا حي يا قيوم برحمتك أستغيث أصلح لي شأني كله ولا تكلني إلى نفسي طرفة عين.',
        source: 'صحيح الحاكم',
        repetition: 1,
        audio: '/audio/ya_hayyu_ya_qayyum.mp3',
      },
      {
        id: 'asbahna-wa-asbahal-mulku-lillah',
        text: 'أصبحنا وأصبح الملك لله، والحمد لله، لا إله إلا الله وحده لا شريك له، له الملك وله الحمد وهو على كل شيء قدير. رب أسألك خير ما في هذا اليوم وخير ما بعده، وأعوذ بك من شر ما في هذا اليوم وشر ما بعده. رب أعوذ بك من الكسل وسوء الكبر، رب أعوذ بك من عذاب في النار وعذاب في القبر. (وفي المساء: أمسينا وأمسى الملك لله...).',
        source: 'صحيح مسلم',
        repetition: 1,
        audio: '/audio/asbahna_wa_asbahal_mulku_lillah.mp3',
      },
      {
        id: 'allahumma-anta-khalaqtani',
        text: 'اللهم أنت خلقتني وأنت تهديني، وأنت تطعمني وأنت تسقيني، وأنت تميتني وأنت تحييني.',
        source: 'صحيح مسلم',
        repetition: 1,
        audio: '/audio/allahumma_anta_khalaqtani.mp3',
      },
      {
        id: 'subhanallahi-wa-bihamdih-100',
        text: 'سبحان الله وبحمده. (مائة مرة).',
        source: 'صحيح مسلم',
        repetition: 100,
        audio: '/audio/subhanallahi_wa_bihamdih_100.mp3',
      },
      {
        id: 'la-ilaha-illallah-wahdahu-10',
        text: 'لا إله إلا الله وحده لا شريك له، له الملك وله الحمد وهو على كل شيء قدير. (عشر مرات، أو مرة عند الكسل).',
        source: 'صحيح البخاري ومسلم',
        repetition: 10,
        audio: '/audio/la_ilaha_illallah_wahdahu_10.mp3',
      },
      {
        id: 'subhanallahi-wa-bihamdih-wa-subhanallahil-azim',
        text: 'سبحان الله وبحمده سبحان الله العظيم.',
        source: 'صحيح البخاري ومسلم',
        repetition: 1,
        audio: '/audio/subhanallahi_wa_bihamdih_wa_subhanallahil_azim.mp3',
      },
    ],
  },
  {
    id: 'azkar-baad-salah',
    category: 'أذكار بعد الصلاة المفروضة',
    sections: [
      {
        id: 'istighfar-baad-salah',
        text: 'أستغفر الله، أستغفر الله، أستغفر الله. (ثلاث مرات).',
        source: 'صحيح مسلم',
        repetition: 3,
        audio: '/audio/istighfar_baad_salah.mp3',
      },
      {
        id: 'allahumma-antas-salam',
        text: 'اللهم أنت السلام ومنك السلام، تباركت يا ذا الجلال والإكرام.',
        source: 'صحيح مسلم',
        repetition: 1,
        audio: '/audio/allahumma_antas_salam.mp3',
      },
      {
        id: 'la-ilaha-illallah-wahdahu-baad-salah',
        text: 'لا إله إلا الله وحده لا شريك له، له الملك وله الحمد وهو على كل شيء قدير، لا حول ولا قوة إلا بالله، لا إله إلا الله ولا نعبد إلا إياه، له النعمة وله الفضل وله الثناء الحسن، لا إله إلا الله مخلصين له الدين ولو كره الكافرون.',
        source: 'صحيح مسلم',
        repetition: 1,
        audio: '/audio/la_ilaha_illallah_wahdahu_baad_salah.mp3',
      },
      {
        id: 'subhanallah-walhamdulillah-allahuakbar',
        text: 'سبحان الله (33 مرة)، والحمد لله (33 مرة)، والله أكبر (33 مرة)، ثم يقول تمام المائة: لا إله إلا الله وحده لا شريك له، له الملك وله الحمد وهو على كل شيء قدير.',
        source: 'صحيح مسلم',
        repetition: 1, // هذا الذكر يوضح التكرار داخل النص
        audio: '/audio/tasbeeh_tahmid_takbir_baad_salah.mp3',
      },
      {
        id: 'ayatul-kursi',
        text: 'الله لا إله إلا هو الحي القيوم لا تأخذه سنة ولا نوم له ما في السماوات وما في الأرض من ذا الذي يشفع عنده إلا بإذنه يعلم ما بين أيديهم وما خلفهم ولا يحيطون بشيء من علمه إلا بما شاء وسع كرسيه السماوات والأرض ولا يؤوده حفظهما وهو العلي العظيم.',
        source: 'آية الكرسي - سنن النسائي',
        repetition: 1,
        audio: '/audio/ayatul_kursi.mp3',
      },
      {
        id: 'qul-huwallahu-ahad',
        text: 'قل هو الله أحد. (مرة بعد كل صلاة، وبعد المغرب والفجر ثلاث مرات).',
        source: 'صحيح الترمذي',
        repetition: 1,
        audio: '/audio/qul_huwallahu_ahad.mp3',
      },
      {
        id: 'qul-aoodhu-birabbil-falaq',
        text: 'قل أعوذ برب الفلق. (مرة بعد كل صلاة، وبعد المغرب والفجر ثلاث مرات).',
        source: 'صحيح الترمذي',
        repetition: 1,
        audio: '/audio/qul_aoodhu_birabbil_falaq.mp3',
      },
      {
        id: 'qul-aoodhu-birabbin-nas',
        text: 'قل أعوذ برب الناس. (مرة بعد كل صلاة، وبعد المغرب والفجر ثلاث مرات).',
        source: 'صحيح الترمذي',
        repetition: 1,
        audio: '/audio/qul_aoodhu_birabbin_nas.mp3',
      },
    ],
  },
  {
    id: 'azkar-nom',
    category: 'أذكار النوم',
    sections: [
      {
        id: 'bismika-allahumma-amutu-wa-ahya',
        text: 'باسمك اللهم أموت وأحيا.',
        source: 'صحيح البخاري',
        repetition: 1,
        audio: '/audio/bismika_allahumma_amutu_wa_ahya.mp3',
      },
      {
        id: 'allahumma-qini-adhabaka',
        text: 'اللهم قني عذابك يوم تبعث عبادك. (ثلاث مرات).',
        source: 'صحيح الترمذي',
        repetition: 3,
        audio: '/audio/allahumma_qini_adhabaka.mp3',
      },
      {
        id: 'subhanallah-walhamdulillah-allahuakbar-nom',
        text: 'سبحان الله (33 مرة)، الحمد لله (33 مرة)، الله أكبر (34 مرة).',
        source: 'صحيح البخاري ومسلم',
        repetition: 1,
        audio: '/audio/tasbeeh_tahmid_takbir_nom.mp3',
      },
      {
        id: 'allahumma-aslamtu-nafsi',
        text: 'اللهم أسلمت نفسي إليك، وفوضت أمري إليك، ووجهت وجهي إليك، وألجأت ظهري إليك، رغبة ورهبة إليك، لا ملجأ ولا منجا منك إلا إليك، آمنت بكتابك الذي أنزلت، وبنبيك الذي أرسلت.',
        source: 'صحيح البخاري ومسلم',
        repetition: 1,
        audio: '/audio/allahumma_aslamtu_nafsi.mp3',
      },
      {
        id: 'bismika-rabbi-wadatu-janbi',
        text: 'باسمك ربي وضعت جنبي وبك أرفعه، إن أمسكت نفسي فارحمها، وإن أرسلتها فاحفظها بما تحفظ به عبادك الصالحين.',
        source: 'صحيح البخاري ومسلم',
        repetition: 1,
        audio: '/audio/bismika_rabbi_wadatu_janbi.mp3',
      },
      {
        id: 'alhamdulillahil-ladhi-at-amana',
        text: 'الحمد لله الذي أطعمنا وسقانا وكفانا وآوانا، فكم ممن لا كافي له ولا مؤوي.',
        source: 'صحيح مسلم',
        repetition: 1,
        audio: '/audio/alhamdulillahil_ladhi_at_amana.mp3',
      },
      {
        id: 'allahumma-rabbassamawati',
        text: 'اللهم رب السماوات ورب الأرض ورب العرش العظيم، ربنا ورب كل شيء، فالق الحب والنوى، ومنزل التوراة والإنجيل والفرقان، أعوذ بك من شر كل ذي شر أنت آخذ بناصيته، اللهم أنت الأول فليس قبلك شيء، وأنت الآخر فليس بعدك شيء، وأنت الظاهر فليس فوقك شيء، وأنت الباطن فليس دونك شيء، اقض عنا الدين وأغننا من الفقر.',
        source: 'صحيح مسلم',
        repetition: 1,
        audio: '/audio/allahumma_rabbassamawati.mp3',
      },
      {
        id: 'qul-ya-ayyuhal-kafirun',
        text: 'قل يا أيها الكافرون... (حتى نهاية السورة).',
        source: 'صحيح الترمذي',
        repetition: 1,
        audio: '/audio/qul_ya_ayyuhal_kafirun.mp3',
      },
      {
        id: 'sura-al-ikhlas-falaq-nas-nom',
        text: 'قراءة سورة الإخلاص، الفلق، الناس (كل سورة ثلاث مرات، ثم تمسح بهما ما استطعت من جسدك تبدأ بهما رأسك ووجهك وما أقبل من جسدك).',
        source: 'صحيح البخاري',
        repetition: 3,
        audio: '/audio/sura_al_ikhlas_falaq_nas_nom.mp3',
      },
    ],
  },
  {
    id: 'azkar-esteiqaz',
    category: 'أذكار الاستيقاظ من النوم',
    sections: [
      {
        id: 'alhamdulillahil-ladhi-ahyana',
        text: 'الحمد لله الذي أحيانا بعد ما أماتنا وإليه النشور.',
        source: 'صحيح البخاري',
        repetition: 1,
        audio: '/audio/alhamdulillahil_ladhi_ahyana.mp3',
      },
      {
        id: 'la-ilaha-illallah-wahdahu-baad-nom',
        text: 'لا إله إلا الله وحده لا شريك له، له الملك وله الحمد وهو على كل شيء قدير، سبحان الله، والحمد لله، ولا إله إلا الله، والله أكبر، ولا حول ولا قوة إلا بالله. (ثم يقول: اللهم اغفر لي أو يدعو فتستجاب دعوته، فإن توضأ وصلى قبلت صلاته).',
        source: 'صحيح البخاري',
        repetition: 1,
        audio: '/audio/la_ilaha_illallah_wahdahu_baad_nom.mp3',
      },
    ],
  },
  {
    id: 'azkar-dukhul-khuruj',
    category: 'أذكار الدخول والخروج من المنزل',
    sections: [
      {
        id: 'bismillahi-walajna',
        text: 'بسم الله ولجنا، وبسم الله خرجنا، وعلى ربنا توكلنا.',
        source: 'سنن أبي داود',
        repetition: 1,
        audio: '/audio/bismillahi_walajna.mp3',
      },
      {
        id: 'bismillahi-tawakkaltu-alal-lah',
        text: 'بسم الله، توكلت على الله، ولا حول ولا قوة إلا بالله.',
        source: 'صحيح الترمذي وأبي داود',
        repetition: 1,
        audio: '/audio/bismillahi_tawakkaltu_alal_lah.mp3',
      },
      {
        id: 'allahumma-inni-aoodhu-bika-min-an-adill',
        text: 'اللهم إني أعوذ بك أن أضل أو أضل، أو أزل أو أزل، أو أظلم أو أظلم، أو أجهل أو يجهل علي.',
        source: 'سنن أبي داود والترمذي',
        repetition: 1,
        audio: '/audio/allahumma_inni_aoodhu_bika_min_an_adill.mp3',
      },
    ],
  },
  {
    id: 'azkar-masjid',
    category: 'أذكار المسجد',
    sections: [
      {
        id: 'dua-dukhul-masjid',
        text: 'أعوذ بالله العظيم وبوجهه الكريم وسلطانه القديم من الشيطان الرجيم. بسم الله والصلاة والسلام على رسول الله، اللهم افتح لي أبواب رحمتك.',
        source: 'صحيح مسلم وأبي داود',
        repetition: 1,
        audio: '/audio/dua_dukhul_masjid.mp3',
      },
      {
        id: 'dua-khuruj-masjid',
        text: 'بسم الله والصلاة والسلام على رسول الله، اللهم إني أسألك من فضلك، اللهم اعصمني من الشيطان الرجيم.',
        source: 'صحيح مسلم وأبي داود',
        repetition: 1,
        audio: '/audio/dua_khuruj_masjid.mp3',
      },
    ],
  },
  {
    id: 'azkar-tamm-wudu',
    category: 'أذكار الوضوء',
    sections: [
      {
        id: 'bismillah-wudu',
        text: 'بسم الله.',
        source: 'سنن أبي داود',
        repetition: 1,
        audio: '/audio/bismillah_wudu.mp3',
      },
      {
        id: 'ashhadu-an-la-ilaha-illa-allah-wudu',
        text: 'أشهد أن لا إله إلا الله وحده لا شريك له، وأشهد أن محمداً عبده ورسوله. اللهم اجعلني من التوابين واجعلني من المتطهرين.',
        source: 'صحيح مسلم والترمذي',
        repetition: 1,
        audio: '/audio/ashhadu_an_la_ilaha_illa_allah_wudu.mp3',
      },
    ],
  },
  {
    id: 'azkar-libas',
    category: 'أذكار اللباس',
    sections: [
      {
        id: 'alhamdulillahil-ladhi-kasani',
        text: 'الحمد لله الذي كساني هذا (الثوب) ورزقنيه من غير حول مني ولا قوة.',
        source: 'صحيح أبي داود',
        repetition: 1,
        audio: '/audio/alhamdulillahil_ladhi_kasani.mp3',
      },
      {
        id: 'dua-new-libas',
        text: 'اللهم لك الحمد أنت كسوتنيه، أسألك خيره وخير ما صنع له، وأعوذ بك من شره وشر ما صنع له.',
        source: 'صحيح أبي داود والترمذي',
        repetition: 1,
        audio: '/audio/dua_new_libas.mp3',
      },
    ],
  },
  {
    id: 'azkar-taam',
    category: 'أذكار الطعام والشراب',
    sections: [
      {
        id: 'bismillah-taam',
        text: 'إذا أكل أحدكم فليذكر اسم الله تعالى، فإن نسي أن يذكر اسم الله تعالى في أوله فليقل: بسم الله أوله وآخره.',
        source: 'صحيح الترمذي وأبي داود',
        repetition: 1,
        audio: '/audio/bismillah_taam.mp3',
      },
      {
        id: 'alhamdulillahil-ladhi-at-amana-saqana',
        text: 'الحمد لله الذي أطعمني هذا ورزقنيه من غير حول مني ولا قوة.',
        source: 'صحيح الترمذي',
        repetition: 1,
        audio: '/audio/alhamdulillahil_ladhi_at_amana_saqana.mp3',
      },
      {
        id: 'dua-min-sharab',
        text: 'إذا شرب أحدكم فلا يتنفس في الإناء، وإذا أراد أن يعود فلينح الإناء ثم ليعود إن شاء.',
        source: 'صحيح مسلم',
        repetition: 1,
        audio: '/audio/dua_min_sharab.mp3',
      },
    ],
  },
  {
    id: 'azkar-safar',
    category: 'أذكار السفر',
    sections: [
      {
        id: 'dua-safar',
        text: 'الله أكبر، الله أكبر، الله أكبر. سبحان الذي سخر لنا هذا وما كنا له مقرنين وإنا إلى ربنا لمنقلبون. اللهم إنا نسألك في سفرنا هذا البر والتقوى، ومن العمل ما ترضى. اللهم هون علينا سفرنا هذا واطو عنا بعده. اللهم أنت الصاحب في السفر والخليفة في الأهل. اللهم إني أعوذ بك من وعثاء السفر وكآبة المنظر وسوء المنقلب في المال والأهل.',
        source: 'صحيح مسلم',
        repetition: 1,
        audio: '/audio/dua_safar.mp3',
      },
      {
        id: 'dua-ruju-safar',
        text: 'آيبون تائبون عابدون لربنا حامدون.',
        source: 'صحيح مسلم',
        repetition: 1,
        audio: '/audio/dua_ruju_safar.mp3',
      },
    ],
  },
  {
    id: 'azkar-rikub-dabbah',
    category: 'أذكار ركوب الدابة/السيارة',
    sections: [
      {
        id: 'bismillahi-subhanalladhi',
        text: 'بسم الله. الحمد لله. سبحان الذي سخر لنا هذا وما كنا له مقرنين وإنا إلى ربنا لمنقلبون.',
        source: 'سنن أبي داود والترمذي',
        repetition: 1,
        audio: '/audio/bismillahi_subhanalladhi.mp3',
      },
    ],
  },
  {
    id: 'azkar-kabir',
    category: 'أذكار عظيمة الأجر',
    sections: [
      {
        id: 'kalimatan-khafifatan',
        text: 'كلمتان خفيفتان على اللسان، ثقيلتان في الميزان، حبيبتان إلى الرحمن: سبحان الله وبحمده، سبحان الله العظيم.',
        source: 'صحيح البخاري ومسلم',
        repetition: 1,
        audio: '/audio/kalimatan_khafifatan.mp3',
      },
      {
        id: 'subhanallahi-wa-bihamdih-adada-khalqih',
        text: 'سبحان الله وبحمده عدد خلقه، ورضا نفسه، وزنة عرشه، ومداد كلماته. (ثلاث مرات في الصباح).',
        source: 'صحيح مسلم',
        repetition: 3,
        audio: '/audio/subhanallahi_wa_bihamdih_adada_khalqih.mp3',
      },
      {
        id: 'la-ilaha-illallah-wahdahu-mih-martan',
        text: 'من قال: لا إله إلا الله وحده لا شريك له، له الملك وله الحمد وهو على كل شيء قدير. في يوم مائة مرة كانت له عدل عشر رقاب، وكتبت له مائة حسنة، ومحيت عنه مائة سيئة، وكانت له حرزاً من الشيطان يومه ذلك حتى يمسي، ولم يأت أحد بأفضل مما جاء به إلا رجل عمل أكثر منه.',
        source: 'صحيح البخاري ومسلم',
        repetition: 100,
        audio: '/audio/la_ilaha_illallah_wahdahu_mih_martan.mp3',
      },
      {
        id: 'astaghfirullah-alladhi-la-ilaha-illa-hu',
        text: 'أستغفر الله العظيم الذي لا إله إلا هو الحي القيوم وأتوب إليه. (من قالها غفر له ذنوبه وإن كان قد فر من الزحف).',
        source: 'صحيح أبي داود والترمذي',
        repetition: 1,
        audio: '/audio/astaghfirullah_alladhi_la_ilaha_illa_hu.mp3',
      },
    ],
  },
  {
    id: 'azkar-hifaz',
    category: 'أذكار الحفظ والتحصين',
    sections: [
      {
        id: 'aoodhu-bikalimatillahil-tammati',
        text: 'أعوذ بكلمات الله التامات من شر ما خلق.',
        source: 'صحيح مسلم',
        repetition: 3,
        audio: '/audio/aoodhu_bikalimatillahil_tammati.mp3',
      },
      {
        id: 'bismillahi-alladhi-la-yaduru-wahuwa',
        text: 'بسم الله الذي لا يضر مع اسمه شيء في الأرض ولا في السماء وهو السميع العليم. (ثلاث مرات صباحاً ومساءً).',
        source: 'صحيح الترمذي وأبي داود',
        repetition: 3,
        audio: '/audio/bismillahi_alladhi_la_yaduru_wahuwa.mp3',
      },
      {
        id: 'allahumma-hifaz-min-shaitan',
        text: 'اللهم إني أعوذ بك من الهم والحزن، وأعوذ بك من العجز والكسل، وأعوذ بك من الجبن والبخل، وأعوذ بك من غلبة الدين وقهر الرجال.',
        source: 'صحيح البخاري',
        repetition: 1,
        audio: '/audio/allahumma_hifaz_min_shaitan.mp3',
      },
    ],
  },
  {
    id: 'azkar-hamd-shukr',
    category: 'أذكار الحمد والشكر',
    sections: [
      {
        id: 'alhamdulillah-katheran',
        text: 'الحمد لله حمداً كثيراً طيباً مباركاً فيه.',
        source: 'صحيح البخاري',
        repetition: 1,
        audio: '/audio/alhamdulillah_katheran.mp3',
      },
      {
        id: 'alhamdulillahil-ladhi-banimatihi',
        text: 'الحمد لله الذي بنعمته تتم الصالحات.',
        source: 'سنن ابن ماجه',
        repetition: 1,
        audio: '/audio/alhamdulillahil_ladhi_banimatihi.mp3',
      },
    ],
  },
  {
    id: 'azkar-istighfar-tawba',
    category: 'أذكار الاستغفار والتوبة',
    sections: [
      {
        id: 'astaghfirullah-wa-atubu-ilayh',
        text: 'أستغفر الله وأتوب إليه. (مائة مرة في اليوم).',
        source: 'صحيح مسلم',
        repetition: 100,
        audio: '/audio/astaghfirullah_wa_atubu_ilayh.mp3',
      },
    ],
  },
  {
    id: 'azkar-saadah-farah',
    category: 'أذكار السعادة والفرح',
    sections: [
      {
        id: 'allahu-akbar-kabira',
        text: 'الله أكبر كبيراً، والحمد لله كثيراً، وسبحان الله بكرة وأصيلاً.',
        source: 'صحيح مسلم',
        repetition: 1,
        audio: '/audio/allahu_akbar_kabira.mp3',
      },
      {
        id: 'subhanallahi-wa-bihamdih-farah',
        text: 'سبحان الله وبحمده، سبحان الله العظيم.',
        source: 'صحيح البخاري ومسلم',
        repetition: 1,
        audio: '/audio/subhanallahi_wa_bihamdih_farah.mp3',
      },
    ],
  },
  {
    id: 'azkar-kasab-rizq',
    category: 'أذكار الرزق وقضاء الدين',
    sections: [
      {
        id: 'allahumma-malikal-mulk',
        text: 'اللهم مالك الملك تؤتي الملك من تشاء وتنزع الملك ممن تشاء وتعز من تشاء وتذل من تشاء بيدك الخير إنك على كل شيء قدير. تولج الليل في النهار وتولج النهار في الليل وتخرج الحي من الميت وتخرج الميت من الحي وترزق من تشاء بغير حساب. رحمن الدنيا والآخرة ورحيمهما، تعطيهما من تشاء وتمنع منهما من تشاء، ارحمني رحمة تغنيني بها عن رحمة من سواك.',
        source: 'صحيح الطبراني',
        repetition: 1,
        audio: '/audio/allahumma_malikal_mulk.mp3',
      },
      {
        id: 'allahumma-ikfini-bihalalika',
        text: 'اللهم اكفني بحلالك عن حرامك، وأغنني بفضلك عمن سواك.',
        source: 'صحيح الترمذي',
        repetition: 1,
        audio: '/audio/allahumma_ikfini_bihalalika.mp3',
      },
    ],
  },
  {
    id: 'azkar-ghadab',
    category: 'أذكار الغضب',
    sections: [
      {
        id: 'aoodhu-billahi-minash-shaytan',
        text: 'أعوذ بالله من الشيطان الرجيم.',
        source: 'صحيح البخاري ومسلم',
        repetition: 1,
        audio: '/audio/aoodhu_billahi_minash_shaytan.mp3',
      },
    ],
  },
  {
    id: 'azkar-karb-huzn',
    category: 'أذكار الكرب والحزن',
    sections: [
      {
        id: 'la-ilaha-illallahul-azimul-halim',
        text: 'لا إله إلا الله العظيم الحليم، لا إله إلا الله رب العرش العظيم، لا إله إلا الله رب السماوات ورب الأرض ورب العرش الكريم.',
        source: 'صحيح البخاري ومسلم',
        repetition: 1,
        audio: '/audio/la_ilaha_illallahul_azimul_halim.mp3',
      },
      {
        id: 'allahumma-rahmataka-arju',
        text: 'اللهم رحمتك أرجو فلا تكلني إلى نفسي طرفة عين، وأصلح لي شأني كله، لا إله إلا أنت.',
        source: 'صحيح أبي داود',
        repetition: 1,
        audio: '/audio/allahumma_rahmataka_arju.mp3',
      },
      {
        id: 'allah-allah-rabbi',
        text: 'الله الله ربي لا أشرك به شيئاً.',
        source: 'سنن أبي داود',
        repetition: 1,
        audio: '/audio/allah_allah_rabbi.mp3',
      },
      {
        id: 'la-ilaha-illa-anta-subhanaka',
        text: 'لا إله إلا أنت سبحانك إني كنت من الظالمين. (دعاء يونس عليه السلام).',
        source: 'صحيح الترمذي',
        repetition: 1,
        audio: '/audio/la_ilaha_illa_anta_subhanaka.mp3',
      },
    ],
  },
  {
    id: 'azkar-istikhara',
    category: 'دعاء الاستخارة',
    sections: [
      {
        id: 'dua-istikhara',
        text: 'اللهم إني أستخيرك بعلمك، وأستقدرك بقدرتك، وأسألك من فضلك العظيم، فإنك تقدر ولا أقدر، وتعلم ولا أعلم، وأنت علام الغيوب. اللهم إن كنت تعلم أن هذا الأمر (وتسمي حاجتك) خير لي في ديني ومعاشي وعاقبة أمري فاقدره لي ويسره لي ثم بارك لي فيه. وإن كنت تعلم أن هذا الأمر شر لي في ديني ومعاشي وعاقبة أمري فاصرفه عني واصرفني عنه واقدر لي الخير حيث كان ثم ارضني به.',
        source: 'صحيح البخاري',
        repetition: 1,
        audio: '/audio/dua_istikhara.mp3',
      },
    ],
  },
  {
    id: 'azkar-marid',
    category: 'أذكار زيارة المريض',
    sections: [
      {
        id: 'la-bas-tahurun',
        text: 'لا بأس طهور إن شاء الله.',
        source: 'صحيح البخاري',
        repetition: 1,
        audio: '/audio/la_bas_tahurun.mp3',
      },
      {
        id: 'as-alullaha-al-azim',
        text: 'أسأل الله العظيم رب العرش العظيم أن يشفيك. (سبع مرات).',
        source: 'سنن أبي داود والترمذي',
        repetition: 7,
        audio: '/audio/as_alullaha_al_azim.mp3',
      },
    ],
  },
  {
    id: 'azkar-mawaqif',
    category: 'أذكار متنوعة لمواقف مختلفة',
    sections: [
      {
        id: 'dua-dalil',
        text: 'اللهم زدنا ولا تنقصنا، وأكرمنا ولا تهنا، وأعطنا ولا تحرمنا، وآثرنا ولا تؤثر علينا، وارضنا وارض عنا.',
        source: 'صحيح الترمذي',
        repetition: 1,
        audio: '/audio/dua_dalil.mp3',
      },
      {
        id: 'dua-kuffaratul-majlis',
        text: 'سبحانك اللهم وبحمدك، أشهد أن لا إله إلا أنت، أستغفرك وأتوب إليك. (دعاء كفارة المجلس).',
        source: 'صحيح الترمذي',
        repetition: 1,
        audio: '/audio/dua_kuffaratul_majlis.mp3',
      },
      {
        id: 'dua-ruyatul-hilal',
        text: 'اللهم أهله علينا باليمن والإيمان والسلامة والإسلام، ربي وربك الله.',
        source: 'صحيح الترمذي',
        repetition: 1,
        audio: '/audio/dua_ruyatul_hilal.mp3',
      },
      {
        id: 'dua-when-it-rains',
        text: 'اللهم صيباً نافعاً.',
        source: 'صحيح البخاري',
        repetition: 1,
        audio: '/audio/dua_when_it_rains.mp3',
      },
      {
        id: 'dua-after-rain',
        text: 'مطرنا بفضل الله ورحمته.',
        source: 'صحيح البخاري ومسلم',
        repetition: 1,
        audio: '/audio/dua_after_rain.mp3',
      },
      {
        id: 'dua-radd-shaitan',
        text: 'أعوذ بكلمات الله التامات التي لا يجاوزهن بر ولا فاجر من شر ما خلق وذرأ وبرأ ومن شر ما ينزل من السماء ومن شر ما يعرج فيها ومن شر ما ذرأ في الأرض ومن شر ما يخرج منها ومن شر فتن الليل والنهار ومن شر طوارق الليل إلا طارقاً يطرق بخير يا رحمن.',
        source: 'سنن أبي داود',
        repetition: 1,
        audio: '/audio/dua_radd_shaitan.mp3',
      },
      {
        id: 'dua-ruyat-halal',
        text: 'اللهم إنا نسألك من خير هذه الريح وخير ما فيها وخير ما أرسلت به، ونعوذ بك من شر هذه الريح وشر ما فيها وشر ما أرسلت به.',
        source: 'صحيح مسلم',
        repetition: 1,
        audio: '/audio/dua_ruyat_halal.mp3',
      },
      {
        id: 'dua-sama-raad',
        text: 'سبحان الذي يسبح الرعد بحمده والملائكة من خيفته.',
        source: 'سنن الترمذي',
        repetition: 1,
        audio: '/audio/dua_sama_raad.mp3',
      },
      {
        id: 'dua-zira-sana',
        text: 'اللهم بارك لنا في ثمرنا، وبارك لنا في مدينتنا، وبارك لنا في صاعنا، وبارك لنا في مدنا.',
        source: 'صحيح مسلم',
        repetition: 1,
        audio: '/audio/dua_zira_sana.mp3',
      },
      {
        id: 'dua-ziyaratul-qubur',
        text: 'السلام عليكم أهل الديار من المؤمنين والمسلمين، وإنا إن شاء الله بكم لاحقون، نسأل الله لنا ولكم العافية.',
        source: 'صحيح مسلم',
        repetition: 1,
        audio: '/audio/dua_ziyaratul_qubur.mp3',
      },
    ],
  },
  // يمكنك إضافة المزيد من الأقسام والأذكار هنا
];

export default azkarData;